# Generated by Django 4.0.6 on 2022-07-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_film_price_alter_film_rel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='film',
            name='director',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
