# Generated by Django 4.0.6 on 2022-07-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0006_category_alter_film_description_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ManyToManyField(to='lista.category'),
        ),
    ]
