# Generated by Django 4.0.6 on 2022-07-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0010_alter_ticket_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='movie',
        ),
    ]
